CREATE TABLE rides (
  id INTEGER NOT NULL PRIMARY KEY  AUTOINCREMENT,
  driver_id INTEGER NOT NULL,
  amount DOUBLE NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(driver_id) REFERENCES drivers(id)
)

